###

POST http://localhost:8080/api/v1/android
Content-Type: application/json

{
  "name": "android1"
}

###

###

POST http://localhost:8080/api/v1/android
Content-Type: application/json

{
  "name": "android2"
}

###

GET http://localhost:8080/api/v1/android

###

PUT http://localhost:8080/api/v1/command
Content-Type: application/json

{
  "author": "Yofaaaa",
  "description": "dasf",
  "time": "2016-05-24T15:54:14",
  "message": "Wake up, Bishop.",
  "priority": "COMMON"
}

###

PUT http://localhost:8080/api/v1/command
Content-Type: application/json

{
  "author": "Ffsa asf",
  "description": "dasf",
  "time": "2016-05-24T15:54:14",
  "message": "Wake up, Bishop.",
  "priority": "CRITICAL"
}

###
// metrics bishop_android_queue_size , bishop_commands_executed_total
GET http://localhost:8080/actuator/prometheus

###

GET http://localhost:8080/test/fail

###

GET http://localhost:8080/test/illegal

###