PUT http://localhost:8080/api/v1/command
Content-Type: application/json

{
  "author": "Ffsa asf",
  "description": "dasf",
  "time": "2016-05-24T15:54:14",
  "message": "Wake up, Bishop.",
  "priority": "CRITICAL"
}
###

PUT http://localhost:8080/api/v1/command
Content-Type: application/json

{
  "author": "Yofaaaa",
  "description": "dasf",
  "time": "2016-05-24T15:54:14",
  "message": "Wake up, Bishop.",
  "priority": "COMMON"
}
###

GET http://localhost:8080/api/v1/android

###

POST http://localhost:8080/api/v1/android
Content-Type: application/json

{
  "name": "add",
  "busy": false
}

###

GET http://localhost:8080/actuator/prometheus

###

GET http://localhost:8080/test/fail

###

GET http://localhost:8080/test/illegal

###